forms_app/urls.py
from django.urls import path
from forms_app.views import *

app_name="forms_app"
urlpatterns = [
    path('contattaci/', contatti, name='contatti'),
    path('', index_contatto, name='index_contatto'),
    path('lista_contatti/', lista_contatti, name='lista_contatti'),
    path('modifica_contatto/<int:pk>', modifica_contatto, name='modifica_contatto'),
    path('elimina_contatto/<int:pk>', elimina_contatto, name='elimina_contatto'),
]

news/urls.py
from django.urls import path
from news.views import *

app_name = 'news'

urlpatterns = [
    path("homepage_news", home, name="homepage_news"),
    path("articoli/", articoloDetailView, name = "articolo_detail"),
    path("articoli/<int:pk>", articoloDetailView, name = "articolo_detail"),
    path("giornalisti/", giornalistaDetailVieW, name = "giornalista_detail"),
    path("giornalisti/<int:pk>", giornalistaDetailVieW, name = "giornalista_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name = "lista_articoli"),
    path("lista_articoli/", listaArticoli, name = "lista_articoli"),
    path("lista_giornalisti/<int:pk>", listaGiornalisti, name = "lista_giornalisti"),
    path("lista_giornalisti/", listaGiornalisti, name = "lista_giornalisti"),
    path("query/", queryBase, name = "query"),
    path('', index_news, name='index_news'),
    path("giornalisti_list_api/", giornalisti_list_api, name='giornalisti_list_api'),
    path("giornalista_api/<int:pk>", giornalista_api, name='giornalista_api'),
    path("articoli_list_api/", articoli_list_api, name='articoli_list_api'),
    path("articolo_api/<int:pk>", articoli_api, name='articoli_api'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace="prima_app")),
    path('', index, name = "index_root"),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('news/', include("news.urls",namespace="news")),
    path('prova_pratica_1/', include("prova_pratica_1.urls",namespace="prova_pratica_1")),
    path('voti/', include("voti.urls",namespace="voti")),
    path('products/', include("products.urls",namespace="products")),
    path('forms_app/', include("forms_app.urls",namespace="forms_app")),
]

urlpatterns += [
    path('accounts/',include('django.contrib.auth.urls')),
]

forms_app/models.py
from django.db import models

# Create your models here.
class Contatto(models.Model):
    nome = models.CharField(max_length=100)
    cognome = models.CharField(max_length=100)
    email = models.CharField(max_length=200)
    contenuto = models.TextField()

forms_app/forms.py
from django import forms
from .models import Contatto

class FormContatto(forms.ModelForm):
    class Meta:
        model = Contatto
        fields = "__all__"

    

forms_app/views.py
from django.shortcuts import render
from .forms import FormContatto
from django.http import HttpResponse
from .models import Contatto
from django.shortcuts  import get_object_or_404,redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

# Create your views here.
def contatti(request):
    if request.method == "POST":
        form = FormContatto(request.POST)
        if form.is_valid():
            print("Il Form è valido!")
            print("NOME: ", form.cleaned_data["nome"])
            print("COGNOME: ", form.cleaned_data["cognome"])
            print("EMAIL: ", form.cleaned_data["email"])
            print("CONTENUTO: ", form.cleaned_data["contenuto"])
            print("Salvo il contatto nel database")
            nuovo_contatto = form.save()
            print("new_post: ", nuovo_contatto)
            print(nuovo_contatto.nome)
            print(nuovo_contatto.cognome)
            print(nuovo_contatto.email)
            print(nuovo_contatto.contenuto)

            return HttpResponse("<h1>Grazie per averci contattato!</h1>")
    else:
        form = FormContatto()
    
    context = {"form": form}
    return render(request, "contatto.html", context)

def index_contatto(request):
    return render(request, "index_contatto.html")

def lista_contatti(request,pk=None):
    if(pk==None):
        contatti = Contatto.objects.all()
    else:
        contatti = Contatto.objects.filter(contatto_id=pk)
    context = {
        'contatti' : contatti,
        'pk' : pk,
    }
    return render(request,'lista_contatti.html',context)

@login_required(login_url="/accounts/login")
def modifica_contatto(request, pk):
    contatto = get_object_or_404(Contatto, id=pk)
    if request.method == "GET":
        form = FormContatto(instance=contatto)
    if request.method == "POST":
        form = FormContatto(request.POST, instance=contatto)
        if form.is_valid():
            form.save()
            return redirect('forms_app:lista_contatti')
        
    context = {'form': form, 'contatto':contatto}
    return render(request, 'modifica_contatto.html',context)

@staff_member_required(login_url="/accounts/login")
def elimina_contatto(request, pk):
    contatto = get_object_or_404(Contatto, id=pk)
    if request.method == "POST":
        contatto.delete()
        return redirect('forms_app:lista_contatti')
    context = {'contatto': contatto}
    return render(request, 'elimina_contatto.html', context)

forms_app/templates/contatto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | Contatti{% endblock head_title %}

{% block content %}
<div class="container">
    <h1> Compila il form di contatto, ti risponderemo quanto prima! </h1>

    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-danger" value="INVIA">
    </form>

</div>
{%endblock content%}

forms_app/templates/elimina_contatto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | Elimina contatto{% endblock head_title %}

{% block content %}
<div class="container">
    <h1> Elimina contatto </h1>
    <form method="post">
        {%csrf_token%}
        {{form|crispy}}
        <input type="submit" class="btn btn-danger" value="CONFERMA ELIMINAZIONE">
    </form>
</div>
{%endblock content%}

forms_app/templates/index_contatto.html
{% extends "base.html" %}

{%block title%} {{block.super}} | Index Contatto{%endblock title%}

{%block content%}
    <ol>
        <li><a href="{% url 'forms_app:contatti'%}"> Contatto </a></li>
        <li><a href="{% url 'forms_app:lista_contatti'%}"> Lista contatti </a></li>
    </ol>
{%endblock content%}

forms_app/templates/lista_contatti.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | Lista contatti{% endblock head_title %}
{%block content%}
    <table class="table table-responsive">
        <tr>
            {%if request.user.is_authenticated%}
            <td> Cancella </td>
            <td> Modifica </td>
            {%endif%}
            <td> Nome </td>
            <td> Cognome </td>
            <td> Email </td>
            <td> Contenuto </td>
        </tr>
    {%for c in contatti%}
        <tr>
            {%if request.user.is_authenticated%}
            <td><a href={%url 'forms_app:elimina_contatto' c.pk%}><i class="fas fa-eraser"></i></a></td>
            <td><a href={%url 'forms_app:modifica_contatto' c.pk%}><i class="far fa-edit"></i></a></td>
            {%endif%}
            <td>{{c.nome}}</td> 
            <td>{{c.cognome}}</td>
            <td>{{c.email}}</td>
            <td>{{c.contenuto}}</td>
        </tr>
    {%endfor%}
    </table>
{%endblock content%}

forms_app/templates/modifica_contatto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{block.super}} | Modifica contatto{% endblock head_title %}

{% block content %}
<div class="container">
    <h1> Modifica contatto </h1>
    <form method="post">
        {%csrf_token%}
        {{form|crispy}}
        <input type="submit" class="btn btn-primary" value="SALVA MODIFICHE">
    </form>
</div>
{%endblock content%}