news/urls.py
from django.urls import path
from news.views import *

app_name = 'news'

urlpatterns = [
    path("homepage_news", home, name="homepage_news"),
    path("articoli/", articoloDetailView, name = "articolo_detail"),
    path("articoli/<int:pk>", articoloDetailView, name = "articolo_detail"),
    path("giornalisti/", giornalistaDetailVieW, name = "giornalista_detail"),
    path("giornalisti/<int:pk>", giornalistaDetailVieW, name = "giornalista_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name = "lista_articoli"),
    path("lista_articoli/", listaArticoli, name = "lista_articoli"),
    path("lista_giornalisti/<int:pk>", listaGiornalisti, name = "lista_giornalisti"),
    path("lista_giornalisti/", listaGiornalisti, name = "lista_giornalisti"),
    path("query/", queryBase, name = "query"),
    path('', index_news, name='index_news'),
    path("giornalisti_list_api/", giornalisti_list_api, name='giornalisti_list_api'),
    path("giornalista_api/<int:pk>", giornalista_api, name='giornalista_api'),
    path("articoli_list_api/", articoli_list_api, name='articoli_list_api'),
    path("articolo_api/<int:pk>", articoli_api, name='articoli_api'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace="prima_app")),
    path('', index, name = "index_root"),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('news/', include("news.urls",namespace="news")),
    path('prova_pratica_1/', include("prova_pratica_1.urls",namespace="prova_pratica_1")),
    path('voti/', include("voti.urls",namespace="voti")),
    path('products/', include("products.urls",namespace="products")),
    path('forms_app/', include("forms_app.urls",namespace="forms_app")),
]

urlpatterns += [
    path('accounts/',include('django.contrib.auth.urls')),
]

prova_pratica_1/urls.py
from django.urls import path
from prova_pratica_1.views import *

app_name="prova_pratica_1"
urlpatterns=[
    path('', index_prova1, name='index_prova1'),
    path('maxmin', maxmin, name='maxmin'),
    path('media', media, name='media'),
    path('voti', voti, name='voti'),
]

voti/urls.py
from django.urls import path
from voti.views import *

app_name = 'voti'

urlpatterns = [
    path("lista_materie", view_a, name="lista_materie"),
    path("voti_studenti", view_b, name = "voti_studenti"),
    path("media_studenti", view_c, name = "media_studenti"),
    path("max_min_voti", view_d, name = "max_min_voti"),
    path('', index_voti, name='index_voti'),
]

voti/models.py
from django.db import models

# Create your models here.

prova_pratica_1/views.py
from django.shortcuts import render
import random

# Create your views here.

def index_prova1(request):
    return render(request, "index_prova1.html")

def maxmin(request):
    num1 = random.randint(1,10)
    num2 = random.randint(1,10)
    somma = num1+num2
    context = {
        'num1' : num1,
        'num2' : num2,
        'somma' : somma,
    }
    return render(request, "maxmin.html", context)

def media(request):
    numeri = []
    i = 1
    somma = 0
    for i in range(30):
        numeri.append(random.randint(1,10))
        somma+=numeri[i]
    media = (somma/30)
    context = {
        'numeri' : [],
        'i' : i,
        'somma' : somma,
        'media' : media,
    }
    return render(request, "media.html", context)

def voti(request):
    context = {
        'tabella' : {
            'Paolo Rossi':6,
            'Matteo Ferrari':9,
            'Luca Verdi':4,
        },
    }
    return render(request, "voti.html",context)

voti/views.py
from django.shortcuts import render

# Create your views here.

voti = {'Giuseppe Gullo':[("Matematica",9,0), ("Italiano",7,3), ("Inglese",7,4), ("Storia",7,4), ("Geografia",5,7)],
            'Antonio Barbera':[("Matematica",8,1), ("Italiano",6,1), ("Inglese",9,0), ("Storia",8,2), ("Geografia",8,1)],
            'Nicola Spina':[("Matematica",7,2), ("Italiano",6,2), ("Inglese",4,3), ("Storia",8,2), ("Geografia",8,2)]}

def index_voti(request):
    return render(request, "index_voti.html")

def view_a(request):
    materie = ["Matematica", "Italiano", "Inglese", "Storia", "Geografia"]
    context = {
        'materie' : materie,
    }
    print(context)
    return render(request, "lista_materie.html", context)

def view_b(request):
    i = 0
    for studente,dati in voti.items():
        print(studente)
        for i in range(4):
            print(voti[studente][i])
    
    context = {
        'voti' : voti,
        'i' : i,
        'studente' : studente,
        'dati' : dati,
    }
    print(context)
    return render(request, "voti_studenti.html", context)

def view_c(request):
    i = 0
    for studente in voti.keys():
        somma = 0
        media = 0
        for i in range(4):
            somma+=voti[studente][i][1]
        media = somma/5
        print(media)
        
    context = {
        'somma' : somma,
        'media' : media,
        'studente' : studente,
        'voti' : voti,
        'i' : i,
        }
    print(context)
    return render(request, "media_studenti.html", context)

def view_d(request):
    voto_massimo = 0
    materie_voto_massimo = ""
    studenti_voto_massimo = ""
    voto_minimo = 0
    matere_voto_minimo = ""
    studenti_voto_minimo = ""
    context = {
        'voto_massimo' : voto_massimo,
        'materie_voto_massimo' : materie_voto_massimo,
        'studenti_voto_massimo' : studenti_voto_massimo,
        'voto_minimo' : voto_minimo,
        'matere_voto_minimo' : matere_voto_minimo,
        'studenti_voto_minimo' : studenti_voto_minimo,
    }
    print(context)
    return render(request, "max_min_voti.html", context)

    

prova_pratica_1/templates/index_prova1.html
{% extends "base.html" %}

{%block title%} {{block.super}} | Index {%endblock title%}

{%block content%}
    <ol>
        <li><a href="{% url 'prova_pratica_1:maxmin'%}"> MaxMin</a></li>
        <li><a href="{% url 'prova_pratica_1:media'%}"> Media</a></li>
        <li><a href="{% url 'prova_pratica_1:voti'%}"> Voti </a></li>
    </ol>
{%endblock content%}

prova_pratica_1/templates/maxmin.html
{% extends "base.html" %}

{%block title%} {{block.super}} | MaxMin {%endblock title%}

{%block content%}
num1 = {{num1}} </br>
num2 = {{num2}}</br>

{% if num1 < num2%}
    <p style="color:red"> {{num1}} </p>
    <p style="color:green"> {{num2}} </p>
{% elif num2 < num1 %}
    <p style="color:green"> {{num1}} </p>
    <p style="color:red"> {{num2}} </p>
{% else %}
    <p style="color:black"> {{num1}} </p>
    <p style="color:black"> {{num2}} </p>
{% endif %}
<p> Somma : {{somma}} </p> 

{%endblock content%}

prova_pratica_1/templates/media.html
{% extends "base.html" %}

{%block title%} {{block.super}} | Media {%endblock title%}

{%block content%}

{% for x in numeri %}
    <i>{{x}}</i><br>
{% endfor %}

media = {{media}}

{% if media < 6%}
    <p style="color:red"> {{media}} </p>
{% elif media > 6%}
    <p style="color:green"> {{media}} </p>
{% else %}
    <p style="color:black"> {{media}} </p>
{% endif %}


{%endblock content%}

prova_pratica_1/templates/voti.html
{% extends "base.html" %}

{%block title%} {{block.super}} | Voti {%endblock title%}

{%block content%}
<h2>Contenuto del dizionario: </h2>
<table id="tabella">
    <thead>
        <tr>
            <th> Studente </th>
            <th> Voto </th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>

{% for key, value in tabella.items %}
    <td>{{ key }}</td>
    <td>{{value}}</td>
{%endfor%}

{%endblock content%}