forms_app/urls.py
from django.urls import path
from forms_app.views import *

app_name="forms_app"
urlpatterns = [
    path('contattaci/', contatti, name='contatti'),
    path('', index_contatto, name='index_contatto'),
    path('lista_contatti/', lista_contatti, name='lista_contatti'),
    path('modifica_contatto/<int:pk>', modifica_contatto, name='modifica_contatto'),
    path('elimina_contatto/<int:pk>', elimina_contatto, name='elimina_contatto'),
]

news/urls.py
from django.urls import path
from news.views import *

app_name = 'news'

urlpatterns = [
    path("homepage_news", home, name="homepage_news"),
    path("articoli/", articoloDetailView, name = "articolo_detail"),
    path("articoli/<int:pk>", articoloDetailView, name = "articolo_detail"),
    path("giornalisti/", giornalistaDetailVieW, name = "giornalista_detail"),
    path("giornalisti/<int:pk>", giornalistaDetailVieW, name = "giornalista_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name = "lista_articoli"),
    path("lista_articoli/", listaArticoli, name = "lista_articoli"),
    path("lista_giornalisti/<int:pk>", listaGiornalisti, name = "lista_giornalisti"),
    path("lista_giornalisti/", listaGiornalisti, name = "lista_giornalisti"),
    path("query/", queryBase, name = "query"),
    path('', index_news, name='index_news'),
    path("giornalisti_list_api/", giornalisti_list_api, name='giornalisti_list_api'),
    path("giornalista_api/<int:pk>", giornalista_api, name='giornalista_api'),
    path("articoli_list_api/", articoli_list_api, name='articoli_list_api'),
    path("articolo_api/<int:pk>", articoli_api, name='articoli_api'),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import *

app_name="prima_app"
urlpatterns=[
    path('homepage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chi_siamo', chi_siamo, name='chi_siamo'),
    path('variabili', variabili, name='variabili'),
    path('', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace="prima_app")),
    path('', index, name = "index_root"),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('news/', include("news.urls",namespace="news")),
    path('prova_pratica_1/', include("prova_pratica_1.urls",namespace="prova_pratica_1")),
    path('voti/', include("voti.urls",namespace="voti")),
    path('products/', include("products.urls",namespace="products")),
    path('forms_app/', include("forms_app.urls",namespace="forms_app")),
]

urlpatterns += [
    path('accounts/',include('django.contrib.auth.urls')),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import *

app_name="seconda_app"
urlpatterns=[
    path('es_if', es_if, name='es_if'),
    path('if_else_elif', if_else_elif, name='if_else_elif'),
    path('es_for', es_for, name='es_for'),
    path('', index_2, name='index_2'),
]

voti/urls.py
from django.urls import path
from voti.views import *

app_name = 'voti'

urlpatterns = [
    path("lista_materie", view_a, name="lista_materie"),
    path("voti_studenti", view_b, name = "voti_studenti"),
    path("media_studenti", view_c, name = "media_studenti"),
    path("max_min_voti", view_d, name = "max_min_voti"),
    path('', index_voti, name='index_voti'),
]

templates/base.html
  <!doctype html>
{% load static %}
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Primo Progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div >
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Prima App
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi Siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Homepage</a>
                <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
                <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
            </div>
          </div>

        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Seconda App
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Es If</a>
                <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">Es If Elif</a>
                <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Es For</a>
            </div>
          </div>

          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                News
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'news:homepage_news'%}">Homepage News</a>
                <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">Lista Articoli</a>
                <a class="dropdown-item" href="{% url 'news:lista_giornalisti'%}">Lista Giornalisti</a>
                <a class="dropdown-item" href="{% url 'news:query'%}">Query</a>
                
            </div>
          </div>

          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Voti
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'voti:lista_materie'%}">Lista Materie</a>
                <a class="dropdown-item" href="{% url 'voti:voti_studenti'%}">Voti Studenti</a>
                <a class="dropdown-item" href="{% url 'voti:media_studenti'%}">Media Studenti</a>
                <a class="dropdown-item" href="{% url 'voti:max_min_voti'%}">Max Min Voti</a>
            </div>
          </div>
        </li>

        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Contatti
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">Contattaci</a>
              <a class="dropdown-item" href="{% url 'forms_app:lista_contatti'%}">Lista contatti</a>
          </div>
        </div>
      </li>

        {%if request.user.is_authenticated %}
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{ request.user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Esci</a>
            </div>
          
          
        {%else%}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}
      </nav>

      <div class="container my-4">
        <!-- servirà per inserire i contenuti della pagina-->
        {%block content%}
        {%endblock content%}
        <!-- servirà per inserire il codice javascript-->

        {%block script%}
        {%endblock script%}
      </div>
      
  </body>
</html>

templates/index_root.html
{% extends "base.html" %}

{%block title%} {{block.super}} | Chi Siamo {%endblock title%}

{%block content%}
    <li><a href="/admin">Pannello admin</a></li>
    <li><a href="{% url 'prima_app:index'%}"> Index Prima App</a></li>
    <li><a href="{% url 'seconda_app:index_2'%}"> Index Seconda App</a></li>
    <li><a href="{% url 'news:index_news'%}"> Index News</a></li>
    <li><a href="{% url 'voti:index_voti'%}"> Index Voti</a></li>
    <li><a href="{% url 'forms_app:index_contatto'%}"> Index Contatto</a></li>
    {%endblock content%}